### ISSUE TITLE
It is not clear how many matrices are there in the collection

### ISSUE THREAD

**Issue by Aznaveh** [ScottKolo/suitesparse-matrix-collection-website#1]
In current format, it is not clear how many matrices are there in the collection.
Also, if you apply any filter you don't know how many matrices you have. 
For example, in 1999, in the paper, "A combined unifrontal/multifrontal method for unsymmetric sparse matrices" by Davis and Duff, mentioned that there are 264 unsymmetric matrices in the collection. I did not find an easy way to compare the number of current unsymmetric matrices in collection.

**Comment by ScottKolo** [comment]
Howdy Mohsen,

Thanks for the suggestion - I have just added this.

**Comment by Aznaveh** [comment]
Great
