### ISSUE TITLE
Expired SSL root certs being served by https://sparse.tamu.edu/

### ISSUE THREAD

**Issue by bonachea** [ScottKolo/suitesparse-matrix-collection-website#16]
Yesterday we noticed we could no longer download files from https://sparse.tamu.edu/ using wget on Linux with OpenSSL 1.0.2k. Eg:

```
wget https://sparse.tamu.edu/RB/Nasa/nasa2146.tar.gz
--2020-06-01 20:57:11--  https://sparse.tamu.edu/RB/Nasa/nasa2146.tar.gz
Resolving sparse.tamu.edu (sparse.tamu.edu)... 34.228.174.189, 34.204.135.175, 34.231.204.249, ...
Connecting to sparse.tamu.edu (sparse.tamu.edu)|34.228.174.189|:443... connected.
ERROR: cannot verify sparse.tamu.edu's certificate, issued by '/C=US/ST=MI/L=Ann Arbor/O=Internet2/OU=InCommon/CN=InCommon RSA Server CA':
  Issued certificate has expired.
To connect to sparse.tamu.edu insecurely, use `--no-check-certificate'.
```

The problem appears to be the server is serving an SSL certificate chain that includes expired certificates for two of the CAs that expired May 30th.

See here for details: https://www.ssllabs.com/ssltest/analyze.html?d=sparse.tamu.edu&s=54.159.115.94&latest

Please fix.

CC: @phhargrove

**Comment by DrTimothyAldenDavis** [comment]
This was an issue that affected all of Texas A&M.  It should be working now.

**Comment by bonachea** [comment]
Looks good - thanks!
