### ISSUE TITLE
Possible to archive compressed mat files?

### ISSUE THREAD

**Issue by dpo** [ScottKolo/suitesparse-matrix-collection-website#25]
Hi,

Matrices in RB and MM format are compressed but matrices in mat format are not. Would it be possible to archive compressed versions of those in order to decrease transfer times?

Thanks!

**Comment by DrTimothyAldenDavis** [comment]
The mat files are compressed already.  MATLAB does that when it creates the
*.mat files.  Compressing them further doesn't help.
