### ISSUE TITLE
500 Proxy Error when trying to download matrices.

### ISSUE THREAD

**Issue by KGHustad** [ScottKolo/suitesparse-matrix-collection-website#3]
When trying to access https://sparse.tamu.edu/MM/Gleich/wb-edu.tar.gz, I get the following error:

>Proxy Error
>The proxy server could not handle the request GET /MM/Gleich/wb-edu.tar.gz.
>
>Reason: Error during SSL Handshake with remote server

This seems to be the case for all matrices I've attempted to download.

**Comment by ScottKolo** [comment]
Thanks for letting us know. One of the SSL certificates on the production server is out of date and currently being replaced. It should be back to normal in the next couple of days. Sorry for the trouble!

There is nothing we can do from a code perspective, so I’m going to close the issue for now.

**Comment by ScottKolo** [comment]
Just a quick update: the SSL issue has been resolved. Feel free to let us know again if you are still having issues or if similar problems pop up again.

**Comment by KGHustad** [comment]
Great! Thanks!
