### ISSUE TITLE
How is `sparse.tamu.edu/files/ssstats.csv` generated?

### ISSUE THREAD

**Issue by cwpearson** [ScottKolo/suitesparse-matrix-collection-website#44]
Hello,

I'm trying to track down a possible bug in the https://github.com/drdarshan/ssgetpy interface - can you tell me how the file hosted at the URL in the title is generated?

Thank you!

**Comment by DrTimothyAldenDavis** [comment]
It's created by the SuiteSparse/MATLAB_Tools/SuiteSparseCollection toolbox,
in MATLAB.
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/MATLAB_Tools/SuiteSparseCollection/ssindex.m
which creates the content for the file and then calls this function to
write the file:
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/MATLAB_Tools/SuiteSparseCollection/sscsv_write.m

**Comment by cwpearson** [comment]
Thank you,

So, if I understand right, this field https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/9d97e0a2fb3d03fac66cd45d3a84338b0a97f368/MATLAB_Tools/SuiteSparseCollection/ssindex.m#L29 distinguishes real from complex nonzero datatypes, and there is no corresponding way to distinguish integer (e.g. https://sparse.tamu.edu/HB/bcsstm01) from real (e.g. https://sparse.tamu.edu/HB/1138_bus) directly using this file?

**Comment by cwpearson** [comment]
Thanks again! 
FYI I asked this question because I was trying to figure out why asking ssgetpy for matrices with "real" datatype produced some integer matrix market files, but I understand why now - ssgetpy parses `ssstats.csv`, so it can't distinguish between "real" and "integer" matrix-market files before they are downloaded. It sounds like ssgetpy would have to find a different metadata source to be able to do this.

**Comment by DrTimothyAldenDavis** [comment]
Right ... the ssstats.csv can't be used for that.

I do have the "RB" type in the MATLAB file, ss_index.mat. That is a
3-character string, and the first letter is r for real (not binary), p for
binary, c for complex, and i for integer.  This field is not in ssstats.csv.
