### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by amontoison** [ScottKolo/suitesparse-matrix-collection-website#53]
`curl` returns the following error
```
curl: (60) SSL certificate problem: certificate has expired                   
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
when I try to download a matrix.
Our Julia package [SuiteSparseMatrixCollection.jl](https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl) is not working anymore due to this issue.

**Comment by DrTimothyAldenDavis** [comment]
Try it now.  I had an issue that led to a delay in getting the new certificate installed.  It is updated now and should work fine.

**Comment by amontoison** [comment]
It works, thanks @DrTimothyAldenDavis !
