### ISSUE TITLE
Expired SSL Certificate for Images

### ISSUE THREAD

**Issue by ScottKolo** [ScottKolo/suitesparse-matrix-collection-website#55]
The SSL certificate for `sparse-files-images.engr.tamu.edu` appears to have expired. Matrix images no longer load correctly.

![Screen Shot 2022-10-23 at 8 12 26 PM](https://user-images.githubusercontent.com/3859035/197429046-3c8bd9bd-ec13-42d7-9909-6a2e115124ef.png)

Related to #53.

**Comment by DrTimothyAldenDavis** [comment]
This should be fixed now.
